### ISSUE TITLE
No results are given anymore 

### ISSUE THREAD

**Issue by Sedatyf** [GoodbyteCo/Letterboxd-Watchlist-Picker#108]
Hi
I've been using watchlist picker on a regular basis for quite some time now and I want to thank you for that! 
But it seems that it doesn't work anymore. Whatever the profile or options you pick, the same error message is given (see attached)

![Screenshot_20230818-214052.png](https://github.com/GoodbyteCo/Letterboxd-Watchlist-Picker/assets/59012307/ec5479fe-6fdf-49b6-891c-9b1a93985572)

Is this related to the API? Unfortunately I'm on my phone I can't open a chrome dev tool

**Comment by HoloPollock** [comment]
Hey thx looking in to it

**Comment by HoloPollock** [comment]
I believe I fixed the issue please look now thx :)

**Comment by HoloPollock** [comment]
There was a small change in the site that brown the way I get data had to do a small update

**Comment by HoloPollock** [comment]
Closing for now. Feel free to reopen if it doesn't work for you

**Comment by Sedatyf** [comment]
Ah sorry I didn't have the notification. Yes everything is fine now, thank you!
