### ISSUE TITLE
Overwrites movie

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/Letterboxd-Watchlist-Picker#11]
Hitting <kbd>submit</kbd> multiple times triggers multiple submit events, and the random movie result ends up getting overwritten by the later requests. At best it makes the experience feel kind of buggy, at worst, the input changed and the first result(s) are incorrect. This might also be a problem for people who choose to "double click" on things.

**Solution:** The `submit()` method should cancel all previous requests, so only the last one shows up. If possible, the loading bar should reset as well.

**Comment by HoloPollock** [comment]
while this still happens does the speed ups make it unlikely to occur so its not super important to fix or should i still fix it

**Comment by qjack001** [comment]
you should still fix it when you have time
