### ISSUE TITLE
Handle public lists

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/letterboxd-watchlist-picker#12]
It would be nice if the service could also work on non-watchlist lists, such as [this one](https://letterboxd.com/dancedancedance/list/boxing-films/). It would use the same search box and be combinable with regular watchlists too. A possible way to distinguish would be to use the remainder of the URL after "letterboxd.com" such as:
```
dancedancedance/list/boxing-films
```
Or perhaps just the username + title of list:
```
dancedancedance/boxing-films
```
The first option is easy to copy/paste, but the latter is easier to type. Obviously both could be included.

**Comment by qjack001** [comment]
One important thing to consider is that many lists—especially very popular ones—are much longer than the average watchlist. For example: [jah776/im-empty-and-aching-and-i-dont-know-why](https://letterboxd.com/jah776/list/im-empty-and-aching-and-i-dont-know-why/).

**Comment by HoloPollock** [comment]
it works now put wee need to add a userfacing way of saying its possible

**Comment by qjack001** [comment]
> Enter your Letterboxd username to get a random film off of your watchlist. Enter multiple usernames by separating with a space or comma, and enter public lists in "username/list-title" format.

Still room for improvement, but good enough for now.
