### ISSUE TITLE
Vue error on runtime

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/letterboxd-watchlist-picker#13]
![image](https://user-images.githubusercontent.com/19389660/90709148-8d66f600-e269-11ea-8fd1-f3991caa5d9a.png)

No noticeable effects on the site. Produced on Chrome.

**Comment by HoloPollock** [comment]
this is an error on a svg so i will not touch as its scary

**Comment by qjack001** [comment]
Source of error: https://github.com/GoodbyteCo/letterboxd-watchlist-picker/blob/cdace62d8c7d112e143f0de21ad66728969326b4/src/components/Film.vue#L23
