### ISSUE TITLE
Backend issue: create a more robust check for lists

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/letterboxd-watchlist-picker#16]
Currently, the backend checks if the query contains "list" to differentiate between `username/list/list-title` and `username/list-title`, adding back the `/list/` if needed. This causes lists with the word "list" in the actual title to break.

For example, this [Weirdo Watchlist](https://letterboxd.com/hamburgersplash/list/weirdo-watchlist/) is unable to be searched: [watchlistpicker.com/?u=hamburgersplash/weirdo-watchlist](https://watchlistpicker.com/?u=hamburgersplash/weirdo-watchlist).

**Comment by HoloPollock** [comment]
i believe this is fixed
