### ISSUE TITLE
Add dark mode / light mode toggle

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/letterboxd-watchlist-picker#32]
Here's a rough sketch of placement and look:

![image](https://user-images.githubusercontent.com/19389660/94226078-a7c56c80-fec4-11ea-8c7b-ad611936a01a.png)

**Comment by HoloPollock** [comment]
ive always had like weird things with how toggle buttons work do you show the current mode or what it will change to
also pls send adobe XD file

**Comment by qjack001** [comment]
i think you show the mode it will change into? but you're right its weird. ill send you the xd file on messenger

**Comment by HoloPollock** [comment]
The only reason I think I could be weird is the animation of changing from sun to moon if vice verse has some
Weird dissonance with changing from dark to light

**Comment by qjack001** [comment]
Very true. Try it the way you feel most makes sense, and we can test it both ways
