### ISSUE TITLE
Filter unreleased movies

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/Letterboxd-Watchlist-Picker#38]
People seem to complain alot about getting recommend films they can't actually go see. Letterboxd treats unreleased films as either having a release date in the future, or no date at all. Films being released later in the current year cannot be determined, but given that the tool is mostly for people looking to get a random result out if a backlog, I think they will rarely want a in-theaters movie (or even a recent release). 

Cutting out all current-year movies and dateless movies will have a fair amount of false-positives. I think they'll be a minority of the film's people will want to see, but nonetheless we should have it be an option to turn on/off in the advanced search. I'm leaning towards opt-in.

- add filter logic to backend
- add switch to advanced search
- update "no films found" text to include reference to no _released_ films, when option is selected

**Comment by HoloPollock** [comment]
If we add this we should add a on hover little warning
