### ISSUE TITLE
Add Percy

### ISSUE THREAD

**Issue by HoloPollock** [GoodbyteCo/Letterboxd-Watchlist-Picker#55]
do we want to add this. [https://github.com/marketplace/percy](https://github.com/marketplace/percy)

**Comment by qjack001** [comment]
this seems like exactly what i was looking for. how does it work in pracitice? have you tried?

**Comment by qjack001** [comment]
@HoloPollock, you got the invite to browserstack/percy, right? What did you think of the test in the other repo? Is it worth spending anymore time trying to figure out?

**Comment by HoloPollock** [comment]
I dont see an invite

**Comment by qjack001** [comment]
> I dont see an invite

i sent it to your goodbyte email

**Comment by qjack001** [comment]
but feel free to login with mine, i put the password in the 1password
