### ISSUE TITLE
Intersection not always working

### ISSUE THREAD

**Issue by qjack001** [GoodbyteCo/Letterboxd-Watchlist-Picker#57]
In the below screenshot, you'll see the recommended film, _Phantom Thread_, despite the fact I have already watched it (therefore no longer on my watchlist). I kept the url in the shot so you can see that intersection is on, and which usernames I entered. Timestamp: `2020-11-15 9:04:39 PM (PST)`.

<img width="1176" alt="Screen Shot of watchlist picker showing phantom thread result" src="https://user-images.githubusercontent.com/19389660/99215029-c991f000-279f-11eb-8dd6-276c109e3cbb.png">

**Comment by HoloPollock** [comment]
Oh whoops lol I'll check it out

**Comment by HoloPollock** [comment]
Self note "the value picked from the list was zero this may have something to do with it"

**Comment by HoloPollock** [comment]
![Screen Shot 2020-11-16 at 11 18 36 PM](https://user-images.githubusercontent.com/24258758/99358254-1d650d80-2862-11eb-8ee3-81001c1257b5.png)

**Comment by HoloPollock** [comment]
figured it out its I check if film has appeared twice before adding where I need to check if film appears users times
